import React, { useState } from 'react';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ExibitionList from './components/ExibitionList';
import Header from './components/Header';
import DataInterface from './interfaces/data';

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(
    'https://api.artic.edu/api/v1/exhibitions?page=1&limit=8',
  );
  const datas = await res.json();
  const { data } = datas;

  return {
    props: {
      data,
    },
  };
};

const Home: NextPage<DataInterface> = ({ data }: DataInterface) => {
  const [exibitions, setExibitions] = useState(data);

  const getMore = async () => {
    // We can get next page with this simple function
    const res = await fetch(
      `https://api.artic.edu/api/v1/exhibitions?page=${
        exibitions.length / 8 + 1
      }&limit=8`,
    );
    const datas = await res.json();
    const newExibitions = datas.data;
    // We destructured current items and concatenate them with new items
    setExibitions((items) => [...items, ...newExibitions]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Exibition App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <ExibitionList exibitions={exibitions} getMore={getMore} />
      </main>
    </div>
  );
};

export default Home;
